# Generated by Django 6.0.2 on 2026-02-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('share_type', models.CharField(max_length=255)),
                ('share_group', models.CharField(max_length=255)),
                ('issue_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
